### PR TITLE
feat: support ESLint 9

### PR DESCRIPTION
**Pull request by brettz9**
feat: support ESLint 9

BREAKING CHANGE:

Requires Node 18

Also:
- chore: use flat config

Note that `context.parserPath` is being removed per https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#context-properties%3A-parseroptions-and-parserpath-being-removed , and although it mentions a theoretical replacement, I didn't see one being supplied on `context.languageOptions` or `context.languageOptions.parserOptions`. But the rule seems to work without it.

I changed from @typescript-eslint/rule-tester as it does not work with flat configs currently.

I removed a couple duplicate test cases (as that was being warned against).

### CODE REVIEW

**Comment by brettz9** [comment]
I'm not sure on resolving the failing CI, except that it works with `--legacy-peer-deps`.

**Comment by gajus** [comment]
Will merge in https://github.com/gajus/eslint-plugin-canonical/pull/35

**Comment by gajus** [comment]
Looks like lint stop does not work.

**Comment by gajus** [comment]
Adding `--legacy-peer-deps` is fine.

**Comment by brettz9** [comment]
I might have to leave you with the TypeScript...

**Pull request merged**
